name: Push MealPlanner.ics
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pushes MealPlanner.ics
      uses: bryanbr23/Recipes@main
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
      with:
        source-files: "/Resources/MealPlanner.ics"
        destination-username: "bryanbr23"
        destination-repository: "bryanbr23/B2HomeStaticWebRepo"
        destination-directory: "/"
        commit-email: "bryan@bredehoeft.com"
