name: Push MealPlanner.ics
on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pushes MealPlanner.ics
      uses: bryanbr23/Recipes@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.foractions }}
      with:
        source_file: 'Resources/MealPlanner.ics'
        destination_repo: 'bryanbr23/B2HomeStaticWebRepo'
        destination_folder: '/'
        user_email: 'bryan@bredehoeft.com'
        user_name: 'bryanbr23'
        commit_message: 'MealPlanner Updated'
      
