name: Push MealPlanner to Static Website
on: push

jobs:

  copy-file:
  
    runs-on: ubuntu-latest
    env:
      ICS_PATH: ${{ github.workspace }}/resources/MealPlanner.ics
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Push ICS to webapp repo
      uses: GuillaumeFalourd/copy-push-files@v1
      with:
        source_files: ${{ env.ICS_PATH }} 
        remote_repository: https://github.com/bryanbr23/B2HomeStaticWebRepo
        access_token: ${{ secrets.ACCESS_TOKEN }}
        target_branch: 'main'
