name: Push MealPlanner to Static Website

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push: 
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #  - cron: '1 0 * * *'

  project_card: 
    types: [created, moved, converted, edited, deleted]
  project_column:
    types: [created, updated, moved, deleted]

jobs:
  copy-file:
  
    runs-on: ubuntu-latest
    env:
      ICS_PATH: ${{ github.workspace }}/resources/MealPlanner.ics
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Push ICS to webapp repo
      uses: GuillaumeFalourd/copy-push-files@v1
      with:
        source_files: ${{ env.ICS_PATH }} 
        remote_repository: https://github.com/bryanbr23/B2HomeStaticWebRepo
        access_token: ${{ secrets.ACCESS_TOKEN }}
        target_branch: 'main'
