name: Push MealPlanner.ics
on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pushes MealPlanner.ics
      uses: bryanbr23/Recipes@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.foractions }}
      with:
        source-files: '/Resources/MealPlanner.ics'
        destination-username: 'bryanbr23'
        destination-repository: 'https://github.com/bryanbr23/Recipes'
        destination-directory: '/'
        commit-email: 'bryan@bredehoeft.com'
