# Version 1.1 -- added copy direct instead of worrying about another action.  Added concurrency as well. 

name: Generate calendar from project columns and cards

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '1 0 * * *'
  project_card: 
    types: [created, moved, converted, edited, deleted]
  project_column:
    types: [created, updated, moved, deleted]

jobs:

  build:
    name: Run python scripts
    runs-on: ubuntu-latest
    env: 
      ICS_PATH: ${{ github.workspace }}/resources/MealPlanner.ics

    steps:

    - name: Check-out repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: pip install -Uq PyGithub

    - name: Generate ICS file
      run: python .github/scripts/generateics.py
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}

    - name: Push ICS to webapp repo
      uses: GuillaumeFalourd/copy-push-files@v1
      with:
        email: ${{ github.actor }}[bot]@users.noreply.github.com
        name: ${{ github.actor }}
        commit_message: calendar_update
        source_files: ${{ env.ICS_PATH }} 
        remote_repository: https://github.com/bryanbr23/B2HomeStaticWebRepo
        target_branch: main
        access_token: ${{ secrets.ACCESS_TOKEN }}
