name: Generate shopping list

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * thu'
  project_card: 
    types: [created, moved, converted, edited, deleted]
  project_column:
    types: [created, updated, moved, deleted]

jobs:

  build:
    name: Generate shopping list markdown file
    runs-on: ubuntu-latest
    
    steps:

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9    

    - name: Install Python dependencies
      run: pip install -Uq PyGithub
        
    - name: Generate shopping list markdown file
      run: python .github/scripts/generateshoppinglist.py
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
        
